management:
  health:
    diskspace:
      enabled: 'true'
    default:
      enabled: 'true'
    db:
      enabled: 'true'
  servlet:
    context-path: /manage
spa:
  default-file: /dist/index.html
spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: 'false'
  sql:
    init:
      data-locations: classpath:import.sql
      mode: always
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: '12341234'
      username: ssafy
    url: jdbc:mysql://192.168.100.156:3306/ssafy_web?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  data:
    web:
      pageable:
        one-indexed-parameters: 'true'
  mvc:
    throw-exception-if-no-handler-found: 'true'
  devtools:
    livereload:
      enabled: 'true'
logging:
  level:
    org:
      sringframework:
        boot: DEBUG
        security: DEBUG
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
    root: INFO
    com:
      samsung:
        security: DEBUG
  file:
    name: ./ssafy-web.log
server:
  servlet:
    encoding:
      enabled: 'true'
      force: 'true'
      charset: UTF-8
    contextPath: /
  address: localhost
  port: '8080'
  compression:
    enabled: 'true'
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
build:
  date: '@build.date@'
jwt:
  expiration: '1296000000'
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'
